#!/bin/sh

# System

if [ -f /etc/X11/xinit/.Xresources ]; then
	xrdb -merge $sysresources
fi

if [ -f /etc/X11/xinit/.Xmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# User

DIR=$XDG_CONFIG_HOME

if [ -z "$DIR" ]; then
	DIR="$HOME/.config"
fi

if [ -f "$DIR/x11/xresources" ]; then
	xrdb -merge "$DIR/x11/xresources"
fi

if [ -f "$DIR/x11/xmodmap" ]; then
	xmodmap "$DIR/x11/xmodmap"
fi

if [ -d "$DIR/x11/xinitrc.d" ] ; then
	for f in $DIR/x11/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Window manager

exec awesome --search "$(luarocks path --lr-path --lua-version 5.3)"
